insert into public.areas (id, name, region, center_lat, center_lng, pandal_count, things_to_do, cafes, restaurants) values
('cluster-1', 'Paikpara', 'North Kolkata', 22.607, 88.3814, 18, ARRAY['Tala Park','Kumartuli idol-makers'' quarter (short walk)','Belgachia riverside']::text[], '[{"name":"Park Cafe, Paikpara"}]'::jsonb, '[{"name":"Garden Cafe Benfish, Tala Park"}]'::jsonb),
('cluster-2', 'Circular Canal (Beleghata)', 'North Kolkata', 22.5829, 88.3754, 17, ARRAY['Beleghata canal-side walk','Birla Industrial & Technological Museum (short ride)']::text[], '[{"name":"Local tea stalls along Beleghata Main Road"}]'::jsonb, '[{"name":"Mitra Café","note":"Kabiraji cutlets since 1920, short ride away"}]'::jsonb),
('cluster-3', 'Jorasanko North', 'North Kolkata', 22.5915, 88.3577, 14, ARRAY['Jorasanko Thakur Bari (Tagore''s ancestral home)','Marble Palace','Nakhoda Mosque','College Street book market (walking distance)']::text[], '[{"name":"Indian Coffee House, College Street"}]'::jsonb, '[{"name":"Putiram","note":"Bengali breakfast & sweets"},{"name":"Paramount","note":"century-old sherbet shop"}]'::jsonb),
('cluster-4', 'Dhakuria', 'South Kolkata', 22.5098, 88.3649, 14, ARRAY['Rabindra Sarobar lake — boating & photography, free entry']::text[], '[{"name":"Cafés along Jodhpur Park Road"}]'::jsonb, '[{"name":"Restaurants near Dhakuria Station"},{"name":"Gariahat food strip","note":"~1.2 km away"}]'::jsonb),
('cluster-5', 'Charu Market (Kalighat)', 'South Kolkata', 22.5023, 88.3455, 13, ARRAY['Kalighat Kali Temple','Lake Market shopping']::text[], '[{"name":"Cafenarumeg","note":"near Kalighat Metro"}]'::jsonb, '[{"name":"Flurys"},{"name":"Paradise Biryani"}]'::jsonb),
('cluster-6', 'Hazra', 'South Kolkata', 22.522, 88.3499, 13, ARRAY['Jatin Das Park','Deshapriya Park (walking distance)']::text[], '[{"name":"Roastery Coffee House, Hazra Road"},{"name":"Bon Appetit","note":"cakes & pastries"}]'::jsonb, '[{"name":"Paradise Biryani, Kalighat"}]'::jsonb),
('cluster-7', 'Azadgarh (Regent Park)', 'South Kolkata', 22.4852, 88.3556, 10, ARRAY['Lake Gardens','Regent Park local markets']::text[], '[{"name":"Cafes around Azadgarh / Regent Park"}]'::jsonb, '[{"name":"Tibetan momo & thukpa joints near Azadgarh"},{"name":"Street food (khau galli)"}]'::jsonb),
('cluster-8', 'Shyam Bazar', 'North Kolkata', 22.5984, 88.3711, 9, ARRAY['Shyampukur Street heritage walk','Hatibagan market']::text[], '[{"name":"Mitra Cafe"}]'::jsonb, '[{"name":"New Punjabi Hotel","note":"90+ years"},{"name":"Allens Kitchen"}]'::jsonb),
('cluster-9', 'Ashok Nagar (Garia / Paschim Putiary)', 'South Kolkata', 22.4807, 88.3373, 9, ARRAY['Gariahat Market shopping strip nearby']::text[], '[{"name":"Fusion cafes around Garia"}]'::jsonb, '[{"name":"Restaurants in the Hindustan Park / Golf Green / Kasba belt"}]'::jsonb),
('cluster-10', 'Alipore', 'South Kolkata', 22.515, 88.3334, 8, ARRAY['Alipore Zoological Gardens (Royal Bengal Tiger)','The Alipore Museum']::text[], '[{"name":"95 Degree Cafe & Bakery, New Alipore"}]'::jsonb, '[{"name":"Restaurants around New Alipore Station"}]'::jsonb),
('cluster-11', 'Bow Bazar North (College Street)', 'Central Kolkata', 22.5748, 88.3632, 8, ARRAY['College Street book market','Asutosh Museum of Indian Art','Presidency University & Calcutta University buildings']::text[], '[{"name":"Indian Coffee House, Bankim Chatterjee Street"}]'::jsonb, '[{"name":"Dilkhusa Cabin","note":"kabiraji cutlets"},{"name":"Mission Cafe","note":"vegetarian"}]'::jsonb),
('cluster-13', 'Ballygunge', 'South Kolkata', 22.5258, 88.3684, 7, ARRAY['Birla Academy of Art & Culture','Birla Mandir']::text[], '[{"name":"Uns Cafe"}]'::jsonb, '[{"name":"6 Ballygunge Place"},{"name":"Barbeque Nation"}]'::jsonb),
('cluster-15', 'Jadavpur', 'South Kolkata', 22.4948, 88.3685, 5, ARRAY['Jadavpur University campus','South City Mall']::text[], '[{"name":"Indian Coffee House, Jadavpur"},{"name":"Chai Addaa"}]'::jsonb, '[{"name":"8B bus stand food strip"},{"name":"South City Mall dining"}]'::jsonb),
('cluster-17', 'Shanti Nagar (Bansdroni)', 'South Kolkata', 22.4734, 88.3623, 4, ARRAY['Bansdroni local market']::text[], '[{"name":"Cafes near Bansdroni Metro"}]'::jsonb, '[{"name":"Kebab / Biryani / Mughlai joints near Bansdroni Metro"}]'::jsonb),
('cluster-18', 'Tollygunge', 'South Kolkata', 22.4963, 88.3344, 4, ARRAY['Tollygunge Club grounds (heritage club)']::text[], '[{"name":"The Royal Bengal Tiger Cafe"},{"name":"Tolly Cafe"}]'::jsonb, '[{"name":"Aminia"},{"name":"A-One Taj Biryani House"}]'::jsonb),
('cluster-20', 'Maniktala', 'South Kolkata', 22.5901, 88.3945, 3, ARRAY['Phool Bagan / Kankurgachi neighbourhood stroll']::text[], '[{"name":"Patisserie by Franziska"}]'::jsonb, '[{"name":"Restaurants on Maniktala Main Road"},{"name":"Kouzina Marine, Salt Lake","note":"short ride"}]'::jsonb),
('cluster-21', 'Dum Dum Park', 'North Kolkata', 22.6209, 88.3934, 5, ARRAY['Walk around Dum Dum Park''s numbered tanks/lakes (Tank No. 1-5) — a genuine local morning/evening walking spot']::text[], '[{"name":"Food & Flora"}]'::jsonb, '[{"name":"Bongo Kitchen"},{"name":"Khatirdari Restaurant"}]'::jsonb)
on conflict (id) do nothing;

insert into public.pandals (id, name, region, lat, lng, crowd_level, area_id, geocoded, rating, theme, visiting_open, visiting_close, nearest_metro_station, nearest_metro_line, access_points, description, tags) values
('north-kolkata-1', '31 Pally Sadharan Durgotsab Samity', 'North Kolkata', 22.6054, 88.38, 'low', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-2', 'Ahiritola Jubak Brinda Durga Puja', 'North Kolkata', 22.596397, 88.353298, 'medium', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-3', 'Amherst Sarbojanin Durgotsab', 'North Kolkata', 22.584256, 88.373447, 'medium', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-4', 'Aswiningar Sarbojanin Durgotsav', 'North Kolkata', 22.5978, 88.3517, 'low', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-5', 'Baghbazar Palli Puja O Pradarshani', 'North Kolkata', 22.6122, 88.3837, 'high', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-6', 'Bandhudal Durgotsob', 'North Kolkata', 22.5982, 88.3768, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-7', 'Beadon Street Sarbojanin Durgotsav', 'North Kolkata', 22.590461, 88.360743, 'low', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-8', 'Belgachia Sadharan Durgotsab', 'North Kolkata', 22.605924, 88.386391, 'medium', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-9', 'Belgachia Yuba Sammilani Durga Puja', 'North Kolkata', 22.604818, 88.387404, 'medium', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-10', 'Bhagabati Park Durga Puja Committee', 'North Kolkata', 22.617629, 88.412869, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-11', 'Bharatiya Tarun Sangha Durga Puja', 'North Kolkata', 22.557586, 88.351027, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-12', 'Biswanath Apartment Sharodutsab', 'North Kolkata', 22.5955, 88.3577, 'medium', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-13', 'Brindaban Matri Mandir Durga Puja', 'North Kolkata', 22.586691, 88.377534, 'low', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-14', 'Calcutta Youth Forum', 'North Kolkata', 22.613, 88.3741, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-15', 'Campbagan Sadharan Durgotsav', 'North Kolkata', 22.5976, 88.3871, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-16', 'Chaltabagan Lohapatty Durga Puja', 'North Kolkata', 22.5806, 88.3822, 'low', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-17', 'Charer Palli Sarbojanin Durgotsab', 'North Kolkata', 22.5966, 88.355, 'medium', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-18', 'Chorebagan Sarbojanin Durgotsab Samity', 'North Kolkata', 22.5911, 88.3869, 'medium', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-19', 'Cossipore Shakti Sangha Durga Puja', 'North Kolkata', 22.61607, 88.378045, 'low', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-20', 'Dakshin Rabindrapally Sarbojanin Durga Puja', 'North Kolkata', 22.5759, 88.383, 'medium', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-21', 'Darjeepara Sarbojanin Durgotsab Samity', 'North Kolkata', 22.5894, 88.3565, 'medium', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-22', 'Deshbandhunagar Sarbojanin Durgotsab', 'North Kolkata', 22.585, 88.3542, 'low', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-23', 'Dum Dum Park Bharat Chakra Durga Puja', 'North Kolkata', 22.621114, 88.392897, 'medium', 'cluster-21', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-24', 'Dum Dum Park Sarbojanin Durga Puja', 'North Kolkata', 22.620008, 88.39391, 'medium', 'cluster-21', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-75', 'Dum Dum Park Tarun Sangha', 'North Kolkata', 22.6198, 88.3944, 'high', 'cluster-21', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-76', 'Dum Dum Park Tarun Dal', 'North Kolkata', 22.6215, 88.3921, 'medium', 'cluster-21', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-77', 'Dum Dum Park Yubak Brinda', 'North Kolkata', 22.6222, 88.3935, 'medium', 'cluster-21', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-25', 'Durbar Mahila Samanya Committee', 'North Kolkata', 22.6159, 88.3784, 'low', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-26', 'Garden Lane Sarbojanin Durgotsab', 'North Kolkata', 22.545331, 88.3432, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-27', 'Goabagan Sarodatsav Sammilani Durga Puja', 'North Kolkata', 22.5889, 88.3623, 'medium', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-28', 'Golaghata Sammilani Durga Puja', 'North Kolkata', 22.596106, 88.400305, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-29', 'Grey Street Sarbojanin Durga Puja', 'North Kolkata', 22.5819, 88.3687, 'medium', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-30', 'Halsibagan Sarbojanin Durgotsab', 'North Kolkata', 22.578913, 88.374682, 'medium', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-31', 'Hari Ghosh Street Sarbojanin', 'North Kolkata', 22.5948, 88.3728, 'low', 'cluster-8', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-32', 'Hari Ghosh Street Swamiji Sangha Sarbojanin Durga Puja', 'North Kolkata', 22.6145, 88.3793, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-33', 'Haritaki Bagan Sarbojanin Durgotsab', 'North Kolkata', 22.586384, 88.372935, 'medium', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-34', 'Hatibagan Nabinpally Sarbojanin Durgotsav', 'North Kolkata', 22.5844, 88.3769, 'high', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-35', 'Jagat Mukherjee Park Durga Puja', 'North Kolkata', 22.601311, 88.366647, 'medium', 'cluster-8', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-36', 'Jokermath Sarbojonin Durga Puja', 'North Kolkata', 22.6102, 88.387, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-37', 'Kailash Bose Street Durga Puja', 'North Kolkata', 22.583193, 88.369077, 'low', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-38', 'Kankurgachi Sarbojanin Durgotsab', 'North Kolkata', 22.580257, 88.390137, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-39', 'Kashi Bose Lane Durga Puja Committee', 'North Kolkata', 22.589362, 88.365247, 'high', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-40', 'Kumartuli Park Sarbojanin Durgotsab Committee', 'North Kolkata', 22.5904, 88.3798, 'high', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-41', 'Kumartuli Sarbojanin Durgotsab', 'North Kolkata', 22.5781, 88.3791, 'medium', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-42', 'Lake View Park Sarbojanin Durgotsav Samity', 'North Kolkata', 22.650587, 88.397627, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-43', 'Mahalla Sarbojanin Durgautsab Samity', 'North Kolkata', 22.6182, 88.3756, 'low', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-44', 'Mitali Kankurgachi Durga Puja', 'North Kolkata', 22.580031, 88.394413, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-45', 'Mohan Bagan Barwari Durga Puja', 'North Kolkata', 22.597336, 88.372751, 'high', 'cluster-8', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-46', 'Mondal Para Sporting Club Durga Puja', 'North Kolkata', 22.5981, 88.3859, 'low', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-47', 'Nainan Para & Jogendra Basak Road Sarbojanin Shree Shree Durgapuja', 'North Kolkata', 22.6172, 88.39, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-48', 'Nalin Sarkar Street Sarbojanin Durgotsab', 'North Kolkata', 22.595346, 88.373396, 'high', 'cluster-8', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-49', 'Nimta Boy''s Athletic Club Sarbojanin Durgotsav', 'North Kolkata', 22.5933, 88.3765, 'low', 'cluster-8', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-50', 'Nimtala Sarbojanin Durgotsab', 'North Kolkata', 22.592771, 88.354808, 'medium', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-51', 'North Tangra Durga Puja', 'North Kolkata', 22.556511, 88.379595, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-52', 'North Tridhara Sarbojanin Durga Puja', 'North Kolkata', 22.519576, 88.355349, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-53', 'Nutan Pally Sarbojanin Durgotsab', 'North Kolkata', 22.520201, 88.349704, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-54', 'Pathuria Ghata Pancher Palli Sarbojanin', 'North Kolkata', 22.588523, 88.357455, 'medium', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-55', 'Ramesh Dutta Street Sarbojanin Durgotsab', 'North Kolkata', 22.589789, 88.360702, 'low', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-56', 'Rammohan Sammilani Durga Puja', 'North Kolkata', 22.579379, 88.369939, 'medium', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-57', 'Sadhukhan Bari Durga Puja', 'North Kolkata', 22.602456, 88.377748, 'medium', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-58', 'Sammilita Lalabagan Sarbojanin Durga Puja', 'North Kolkata', 22.586, 88.3734, 'low', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-59', 'Sarkar Bagan Sammilita Sangha Durga Puja', 'North Kolkata', 22.5835, 88.3633, 'medium', 'cluster-3', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-60', 'Sater Palli Sarbojanin Durgotsav', 'North Kolkata', 22.606, 88.3852, 'medium', 'cluster-1', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-61', 'Shyambazar Nabin Sangha Durga Puja', 'North Kolkata', 22.598694, 88.375501, 'low', 'cluster-8', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-62', 'Signum Aristo Residential Puja', 'North Kolkata', 22.6053, 88.3652, 'medium', 'cluster-8', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-63', 'Sikdar Bagan Sadharan Durgotsov', 'North Kolkata', 22.596611, 88.372616, 'medium', 'cluster-8', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-64', 'Simla Sporting Club Durga Puja', 'North Kolkata', 22.588366, 88.377228, 'high', 'cluster-2', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-65', 'Sovabazar Sarbojanin Durgotsav', 'North Kolkata', 22.597529, 88.354934, 'high', 'cluster-3', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-66', 'Sreebhumi Sporting Club Durga Puja', 'North Kolkata', 22.798903, 88.37781, 'high', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-67', 'Tala Barowari Durgotsab', 'North Kolkata', 22.606351, 88.378426, 'high', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-68', 'Tala Dakshin Pally Durgotsav Committee', 'North Kolkata', 22.6031, 88.3646, 'medium', 'cluster-8', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-69', 'Tala Park 15 Pally Durga Puja', 'North Kolkata', 22.605245, 88.379439, 'medium', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-70', 'Telengabagan Sarbojanin Durgotsab', 'North Kolkata', 22.5782, 88.3702, 'low', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-71', 'Ultadanga Jagarani Sangha Durga Puja', 'North Kolkata', 22.5751, 88.3673, 'medium', 'cluster-2', false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-72', 'Ultadanga Pallyshree Durga Puja', 'North Kolkata', 22.59579, 88.38444, 'medium', 'cluster-1', true, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-73', 'Ultadanga Sangrami Durga Puja', 'North Kolkata', 22.5746, 88.3643, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('north-kolkata-74', 'Young Citizens Club Durga Puja', 'North Kolkata', 22.545563, 88.37792, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-75', '21 Pally Sarbojanin Durgotsab Samiti', 'South Kolkata', 22.4866, 88.3549, 'low', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-76', '22 Palli Sarodotsav', 'South Kolkata', 22.503, 88.3552, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-77', '25 Pally Durga Puja', 'South Kolkata', 22.501, 88.3419, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-78', '64 Pally Durgotsab Committee', 'South Kolkata', 22.4994, 88.3499, 'low', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-79', '66 Pally Sarbojanin Durgotsab Committee', 'South Kolkata', 22.5143, 88.3289, 'medium', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-80', '70 Pally Sarbojanin Durga Puja', 'South Kolkata', 22.4958, 88.3454, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-81', '95 Pally Jodhpur Park Durga Puja', 'South Kolkata', 22.505606, 88.363674, 'low', 'cluster-4', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-82', 'Abasar Sarbojanin Durgotsab Committee', 'South Kolkata', 22.528139, 88.348669, 'medium', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-83', 'Abasorika Durgotsav Committee', 'South Kolkata', 22.4852, 88.3538, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-84', 'Adi Ballygunge Sarbojanin Durga Puja', 'South Kolkata', 22.531728, 88.372075, 'low', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-85', 'Adi Dakshin Kalikata Barowari Samittee', 'South Kolkata', 22.42765, 88.401705, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-86', 'Agradut Udaya Sangha Durga Puja', 'South Kolkata', 22.5067, 88.35, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-87', 'Arunodaya Adhibashi Brinder Durga Puja', 'South Kolkata', 22.681692, 88.281255, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-88', 'Avijan Gandhi Colony', 'South Kolkata', 22.5084, 88.3438, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-89', 'Babu Bagan Durga Puja', 'South Kolkata', 22.508452, 88.369121, 'medium', 'cluster-4', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-90', 'Badamtala Ashar Sangha Durga Puja', 'South Kolkata', 22.517927, 88.344165, 'low', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-91', 'Baghajatin B and C Block Durgotsav Committee', 'South Kolkata', 22.483881, 88.375445, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-92', 'Baghajatin Tarun Sangha Durgotsav', 'South Kolkata', 22.482739, 88.386671, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-93', 'Baishnabghata Paschimpara Sarbojanin Durgotsab', 'South Kolkata', 22.514, 88.3593, 'low', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-94', 'Ballygunge Cultural Association Durga Puja', 'South Kolkata', 22.528034, 88.365908, 'high', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-95', 'Ballygunge Pally Sarbojanin Durgotsab Committee', 'South Kolkata', 22.526928, 88.366922, 'medium', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-96', 'Bansdroni Sammilita Sarbojanin Durgotsab Committee', 'South Kolkata', 22.473586, 88.360673, 'low', 'cluster-17', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-97', 'Bediadanga Sarbojanin Durgotsav Committee', 'South Kolkata', 22.478, 88.3395, 'medium', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-98', 'Beltala Sarbojanin Durgotsab', 'South Kolkata', 22.683456, 88.368746, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-99', 'Bengal United Club Durga Puja', 'South Kolkata', 22.5128, 88.3361, 'low', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-100', 'Bhawanipore Mahapuja Samity', 'South Kolkata', 22.4856, 88.3494, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-101', 'Bhowanipore De Bari Durga Puja', 'South Kolkata', 22.532584, 88.345443, 'medium', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-102', 'Bhowanipore Mitra Bari Durga Puja', 'South Kolkata', 22.531478, 88.346456, 'low', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-103', 'Bhowanipur 75 Palli Durga Puja', 'South Kolkata', 22.5001, 88.3372, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-104', 'Bhowanipur Muktadal Durga Puja', 'South Kolkata', 22.4935, 88.3462, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-105', 'Bhowanipur Ritwik Club Durga Puja Committee', 'South Kolkata', 22.4961, 88.3696, 'low', 'cluster-15', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-106', 'Bhowanipur Sarbojanin Durgotsav', 'South Kolkata', 22.5113, 88.366, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-107', 'Bhowanipur Students Club Sarbojanin Durga Puja', 'South Kolkata', 22.5223, 88.3565, 'medium', 'cluster-6', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-108', 'Bhowanipur Swadhin Sangha Durga Puja', 'South Kolkata', 22.4814, 88.3359, 'low', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-109', 'Bhowanipur Udayan Club Durga Puja', 'South Kolkata', 22.4865, 88.348, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-110', 'Bidhan Nagar South Atheletics Club', 'South Kolkata', 22.591149, 88.391259, 'medium', 'cluster-20', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-111', 'Bidhanpally Purbapara Sarbojanin', 'South Kolkata', 22.5015, 88.337, 'low', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-112', 'Bosepukur Talbagan Sarbojanin', 'South Kolkata', 22.4826, 88.3567, 'high', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-113', 'Brahmapur Harisava Sarbojanin Durgotsab', 'South Kolkata', 22.4975, 88.3691, 'medium', 'cluster-15', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-114', 'Chetla Agrani Club Durga Puja', 'South Kolkata', 22.516435, 88.337189, 'high', 'cluster-10', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-115', 'Chetla Sarbasadharaner Durgotsab', 'South Kolkata', 22.4817, 88.3287, 'medium', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-116', 'Coal India Puja Committee Durga Puja', 'South Kolkata', 22.582139, 88.447298, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-117', 'Dakshin Kolkata Sarbojanin Durgotsab', 'South Kolkata', 22.518565, 88.352614, 'low', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-118', 'Dakshin Kolkata Tarun Samity Durga Puja', 'South Kolkata', 22.517459, 88.353627, 'medium', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-119', 'Deshapriya Park Durga Puja', 'South Kolkata', 22.518435, 88.353515, 'high', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-120', 'Dhakuria Pragati Sangha Durga Puja', 'South Kolkata', 22.518, 88.3392, 'low', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-121', 'Dhakuria Sarbojanin Durgotsab', 'South Kolkata', 22.509107, 88.371131, 'medium', 'cluster-4', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-122', 'Ekdalia Evergreen Club Durga Puja', 'South Kolkata', 22.521253, 88.36596, 'high', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-123', 'Falguni Sangha Durga Puja', 'South Kolkata', 22.4876, 88.3414, 'low', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-124', 'Garfa Sarbojanin Durgotsav', 'South Kolkata', 22.506145, 88.383976, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-125', 'Goala Para Five Star Sporting Club', 'South Kolkata', 22.5196, 88.3711, 'medium', 'cluster-13', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-126', 'Golpark Sarbojanin Durgotsab Committee', 'South Kolkata', 22.513432, 88.401745, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-127', 'Gopal Nagar Kalyan Sangha Durga Puja', 'South Kolkata', 22.498555, 88.331492, 'medium', 'cluster-18', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-128', 'Harish Park Sarbojanin Durgotsab Samity', 'South Kolkata', 22.530533, 88.343728, 'medium', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-129', 'Hindustan Pally Durga Puja Committee', 'South Kolkata', 22.531637, 88.374004, 'low', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-130', 'Jagaran Club Durga Puja', 'South Kolkata', 22.504815, 88.370836, 'medium', 'cluster-4', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-131', 'Jubamaitry Kalighat Durga Puja', 'South Kolkata', 22.5212, 88.3279, 'medium', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-132', 'Kalighat Nepal Bhattacharjee Street Club', 'South Kolkata', 22.4887, 88.3558, 'low', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-133', 'Kansaripara Sarbojanin Sarodotsab Committee', 'South Kolkata', 22.537035, 88.341149, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-134', 'Kasba R.K. Chatterjee Road Adhibasi Brinda Durga Puja', 'South Kolkata', 22.51436, 88.405655, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-135', 'Kasba Renaissance Club', 'South Kolkata', 22.4951, 88.3426, 'low', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-136', 'Kasba Shakti Sangha Pallybasi Durgotsav Samity', 'South Kolkata', 22.4857, 88.358, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-137', 'Ketopole Sammilani Durga Puja', 'South Kolkata', 22.5172, 88.3498, 'medium', 'cluster-6', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-138', 'Keyatala Pally Samity Durga Puja', 'South Kolkata', 22.515428, 88.362448, 'low', 'cluster-4', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-139', 'Kheyali Sangha Durga Puja', 'South Kolkata', 22.61549, 88.380864, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-140', 'Khidderpore Sarbojanin Durgotsab', 'South Kolkata', 22.538698, 88.317565, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-141', 'Khidderpur 75 Pally Sarbojanin Durgotsab Committee', 'South Kolkata', 22.552326, 88.343068, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-142', 'Kidderpore Jubaghosthi Durga Puja', 'South Kolkata', 22.5145, 88.3663, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-143', 'Kidderpore Pally Saradiya Durga Puja', 'South Kolkata', 22.507, 88.3567, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-144', 'Lake Gardens Peoples Association Durga Puja', 'South Kolkata', 22.508055, 88.353329, 'low', 'cluster-5', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-145', 'Lake Youth Corner Durga Puja', 'South Kolkata', 22.5193, 88.3391, 'medium', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-146', 'Mahamayatala Sarbojanin Durgotsab', 'South Kolkata', 22.5142, 88.369, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-147', 'Megacity Residents Puja Committee', 'South Kolkata', 22.588866, 88.499107, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-148', 'Mohila Mahal Club Durga Puja', 'South Kolkata', 22.4827, 88.3603, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-149', 'Monohar Pukur Baisakhi Sangha', 'South Kolkata', 22.5068, 88.3425, 'medium', 'cluster-5', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-150', 'Mudiali Club Sarbojanin Durga Puja', 'South Kolkata', 22.510075, 88.346626, 'high', 'cluster-5', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-151', 'N.S.C. Sports Club Durga Puja', 'South Kolkata', 22.512899, 88.348545, 'medium', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-152', 'Naktala Udayan Sangha Durga Puja', 'South Kolkata', 22.474361, 88.366516, 'high', 'cluster-17', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-153', 'Naskarpara Sarbojanin Durgotsav', 'South Kolkata', 22.473175, 88.360136, 'low', 'cluster-17', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-154', 'New Alipore Suruchi Sangha Durga Puja', 'South Kolkata', 22.511165, 88.328112, 'high', 'cluster-10', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-155', 'New Santoshpur Adi Durgotsab', 'South Kolkata', 22.4911, 88.3336, 'medium', 'cluster-18', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-156', 'Paddapukur Barwari Samity', 'South Kolkata', 22.505025, 88.302958, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-157', 'Paddapukur Youth Association Durga Puja', 'South Kolkata', 22.503918, 88.303971, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-158', 'Pally Mangal Samity Durga Puja', 'South Kolkata', 22.584285, 88.358102, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-159', 'Panchanna Gram Adhibasibrinda', 'South Kolkata', 22.53102, 88.395862, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-160', 'Paschim Putiary Sarbojanin Nabo Durgotsav', 'South Kolkata', 22.480362, 88.33779, 'medium', 'cluster-9', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-161', 'Patuli Sarbojanin Durgotsab', 'South Kolkata', 22.4981, 88.3329, 'medium', 'cluster-18', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-162', 'Peyarabagan Sarbojanin Durgotsab', 'South Kolkata', 22.518, 88.3625, 'low', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-163', 'Picnic Sunrise Club', 'South Kolkata', 22.4976, 88.3397, 'medium', 'cluster-18', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-164', 'Pragati Sangha Durga Puja', 'South Kolkata', 22.590109, 88.395606, 'medium', 'cluster-20', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-165', 'Pragati Sangha Durgotsab Committee', 'South Kolkata', 22.589003, 88.39662, 'low', 'cluster-20', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-166', 'Purbachal Residents Sarbojanin Durgotsav', 'South Kolkata', 22.510497, 88.395981, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-167', 'Putiary Sarbojanin Durgotsab Committee', 'South Kolkata', 22.479256, 88.338803, 'medium', 'cluster-9', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-168', 'Ramgarh Satapally Sarbojanin Durgotsav Committee', 'South Kolkata', 22.4931, 88.3706, 'low', 'cluster-15', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-169', 'Rashbehari Suhrid Sangha', 'South Kolkata', 22.4826, 88.359, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-170', 'Russa Madhyapally Sarbojanin Durgotsav', 'South Kolkata', 22.4883, 88.3662, 'medium', 'cluster-15', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-171', 'Sahapur Suhrid Sangha Durga Puja Committee', 'South Kolkata', 22.5195, 88.3489, 'low', 'cluster-6', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-172', 'Sammilani Durga Puja', 'South Kolkata', 22.5066, 88.3601, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-173', 'Sanghasree Kalighat Durga Puja', 'South Kolkata', 22.4855, 88.3603, 'medium', 'cluster-7', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-174', 'Santoshpur Avenue South', 'South Kolkata', 22.49244, 88.392152, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-175', 'Santoshpur Lake Pally Durga Puja', 'South Kolkata', 22.491427, 88.383691, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-176', 'Santoshpur Trikon Park Durgotsab', 'South Kolkata', 22.4804, 88.3348, 'medium', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-177', 'Shibmandir Sarbojanin Durgotsab Samiti', 'South Kolkata', 22.4778, 88.3342, 'low', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-178', 'Singhi Park Sarbojanin Durga Puja', 'South Kolkata', 22.521224, 88.363011, 'high', 'cluster-13', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-179', 'Sonarpur Sarbojanin Durgotsav Puja Committee', 'South Kolkata', 22.440875, 88.424637, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-180', 'Sri Sri Sarbojanin Durga Puja', 'South Kolkata', 22.4794, 88.3444, 'low', 'cluster-9', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-181', 'Surya Nagar Sarbojanin Durga Puja', 'South Kolkata', 22.47248, 88.361686, 'medium', 'cluster-17', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-182', 'Tridhara Sammilani Durga Puja', 'South Kolkata', 22.51847, 88.356362, 'high', 'cluster-6', true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-183', 'Tulipians Durgotsav', 'South Kolkata', 22.5068, 88.3303, 'low', 'cluster-10', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-184', 'Udayan Kidderpore Durga Puja', 'South Kolkata', 22.5028, 88.3651, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-185', 'Upohar Utsav Committee', 'South Kolkata', 22.4991, 88.3668, 'medium', 'cluster-15', false, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-186', 'VIP Nagar Sarbojanin Durga Puja Committee', 'South Kolkata', 22.523695, 88.398863, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('south-kolkata-187', 'Westend Park Sarbojanin Durga Puja', 'South Kolkata', 22.505, 88.3668, 'medium', 'cluster-4', false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-188', '14 Pally Udayan Sangha', 'Central Kolkata', 22.545646, 88.321646, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-189', '37 Pally Sarbojanin Durgotsab', 'Central Kolkata', 22.5789, 88.3689, 'medium', 'cluster-11', false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-190', '47 Pally Jubak Brinda Durga Puja', 'Central Kolkata', 22.5559, 88.3689, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-191', 'Central Calcutta Youth Association', 'Central Kolkata', 22.572486, 88.358743, 'low', 'cluster-11', true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-192', 'College Square Sarbojanin Durgotsav', 'Central Kolkata', 22.574525, 88.364464, 'high', 'cluster-11', true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-193', 'Entally Matribhumi Durga Puja', 'Central Kolkata', 22.5438, 88.3542, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-194', 'Entally Sarbojanin Sri Sri Durga Puja', 'Central Kolkata', 22.5803, 88.3414, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-195', 'Interact Club of Chowringhee High School Sarbojanin Durga Puja', 'Central Kolkata', 22.5728, 88.3517, 'medium', 'cluster-11', false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-196', 'Kanai Dhar Lane Adhibasi Brinda', 'Central Kolkata', 22.571575, 88.365868, 'medium', 'cluster-11', true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-197', 'Machua Bazar Sarbajanik Durga Puja Samity', 'Central Kolkata', 22.580781, 88.363219, 'low', 'cluster-11', true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-198', 'Md. Ali Park Durga Puja', 'Central Kolkata', 22.5681, 88.3375, 'high', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-199', 'New Market Sarbojanin Sri Sri Durga Puja', 'Central Kolkata', 22.560152, 88.352956, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-200', 'Pallir Yubak Brinda Durga Puja', 'Central Kolkata', 22.5631, 88.3576, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-201', 'Santosh Mitra Square Durga Puja', 'Central Kolkata', 22.565863, 88.365539, 'high', 'cluster-11', true, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-202', 'Shishu Palan Foundation', 'Central Kolkata', 22.5814, 88.3672, 'medium', 'cluster-11', false, null, null, null, null, null, null, '{}', null, '{}'),
('central-kolkata-203', 'Wellington Nagarik Kalyan Samity Durga Puja', 'Central Kolkata', 22.5597, 88.3609, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-204', '2 No Basudebpur Sarbojanin Durga Puja', 'West Kolkata', 22.517648, 88.131751, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-205', '7er Pally Sarbojanin Durga Puja Committee', 'West Kolkata', 22.578, 88.3037, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-206', 'Acharya Prafulla Sangha', 'West Kolkata', 22.576833, 88.392715, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-207', 'Ajeya Sanghati Durga Puja', 'West Kolkata', 22.480962, 88.337529, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-208', 'Barisha Kumarpara Youngs'' Club Durga Puja', 'West Kolkata', 22.6026, 88.3056, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-209', 'Barisha Maitree Sangha Durgotsab', 'West Kolkata', 22.5903, 88.2996, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-210', 'Barisha Milani Sangha Durga Puja', 'West Kolkata', 22.5708, 88.3252, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-211', 'Barisha Netaji Sangha Durga Puja', 'West Kolkata', 22.485726, 88.315341, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-212', 'Barisha Sarbojanin Durgotsab', 'West Kolkata', 22.456229, 88.307162, 'high', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-213', 'Barisha Saterpalli Sammilani Durga Puja', 'West Kolkata', 22.5992, 88.3176, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-214', 'Behala 11 Pally Durga Puja', 'West Kolkata', 22.501572, 88.320943, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-215', 'Behala Arunoday Samity', 'West Kolkata', 22.5983, 88.3225, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-216', 'Behala Buroshibtala Janakalyan Sangha Durga Puja', 'West Kolkata', 22.5684, 88.2956, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-217', 'Behala Debdaru Fatak Durga Puja', 'West Kolkata', 22.5662, 88.3141, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-218', 'Behala Mitra Sangha Durga Puja', 'West Kolkata', 22.500466, 88.321957, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-219', 'Behala Mukul Sangha Durgotsab', 'West Kolkata', 22.6004, 88.3145, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-220', 'Bishalaxmitala Sarbojanin Durga Puja', 'West Kolkata', 22.5905, 88.3027, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-221', 'Genexx Valley Durga Puja', 'West Kolkata', 22.5833, 88.3077, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-222', 'Haridevpur New Sporting Club Durga Puja', 'West Kolkata', 22.6056, 88.2896, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-223', 'Haru Chandra Sporting Club', 'West Kolkata', 22.6012, 88.3152, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-224', 'Jayasree Sarbojanin Durgotsab Samity', 'West Kolkata', 22.5646, 88.303, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-225', 'Joyrampur Sarbojanin Durga Puja Committee', 'West Kolkata', 22.575, 88.3157, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-226', 'Monmohan Park Sarbojanin Durgotsab', 'West Kolkata', 22.66882, 88.34257, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-227', 'Nabarun Sangha Durga Puja', 'West Kolkata', 22.702861, 88.371664, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-228', 'Palli Asar Sporting Club Durga Puja', 'West Kolkata', 22.6039, 88.3047, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-229', 'Palli Unnayan Samity Durga Puja', 'West Kolkata', 22.478133, 88.34221, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-230', 'Parnasree Club Sarbojanin Durgotsav', 'West Kolkata', 22.510188, 88.306175, 'high', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-231', 'Sahapur Colony East Durga Puja', 'West Kolkata', 22.5872, 88.3028, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-232', 'Sahapur Friends Association Sarbojanin', 'West Kolkata', 22.5818, 88.2969, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-233', 'Sahapur Mitali Sangha Durga Puja', 'West Kolkata', 22.5665, 88.2903, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-234', 'Sahapur Nabashakti Sangha Durga Puja', 'West Kolkata', 22.5914, 88.3067, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-235', 'Sahapur Panchabatitala Sammilani Durga Puja', 'West Kolkata', 22.5853, 88.3074, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-236', 'Sahapur Sarbojanin Durgotsab Committee', 'West Kolkata', 22.50588, 88.326403, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-237', 'Shyam Sunder Pallybasi Brinda', 'West Kolkata', 22.6028, 88.2935, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-238', 'Sreemapally Sarbojanin Durga Puja', 'West Kolkata', 22.5741, 88.3006, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-239', 'State Bank Park Sarbojanin Durga Puja', 'West Kolkata', 22.55296, 88.356451, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-240', 'Swamiji Sarak Sarbojanin Durgotsab', 'West Kolkata', 22.489183, 88.329613, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('west-kolkata-241', 'Taratala Milantirtha Institute', 'West Kolkata', 22.5902, 88.3123, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-242', 'Beleghata Sarkar Bazar Durga Puja', 'East Kolkata', 22.5888, 88.4206, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-243', 'Beliaghata 33 Palli Durga Puja', 'East Kolkata', 22.550656, 88.403917, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-244', 'EKTP Phase 2 Abasik Puja Samity', 'East Kolkata', 22.511746, 88.400357, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-245', 'Jawpur Bayam Samity Durga Puja', 'East Kolkata', 22.5489, 88.413, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-246', 'Judge Bagan Sarbojanin Durgotsab', 'East Kolkata', 22.525294, 88.331311, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-247', 'Kanjial Para Puja Samity Durga Puja', 'East Kolkata', 22.635074, 88.483049, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-248', 'Nabapally Adhibashi Brinda Durga Puja', 'East Kolkata', 22.514669, 88.390413, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-249', 'Netaji Sporting Club Durga Puja', 'East Kolkata', 22.480993, 88.346, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-250', 'Purba Kalikata Sarbojanin Durgotsav', 'East Kolkata', 22.474452, 88.311771, 'high', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-251', 'Purbanchal Prabhati Sangha Durga Puja', 'East Kolkata', 22.5694, 88.4027, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-252', 'Sixemes Cooperative Housing Durgotsav', 'East Kolkata', 22.5722, 88.4187, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-253', 'Sree Sree Durga Puja Committee, Rabindrapally', 'East Kolkata', 22.768768, 88.386142, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-254', 'AJ Block Durga Puja', 'East Kolkata', 22.572646, 88.363895, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-255', 'BD Block Sarbojanin Durgotsab Committee', 'East Kolkata', 22.60359, 88.427041, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-256', 'BJ Block Saradotsav Committee', 'East Kolkata', 22.5597, 88.4125, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-257', 'BL Block Durga Puja', 'East Kolkata', 22.560589, 88.351415, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('east-kolkata-258', 'Prafulla Kanan Sarbojanin Durgotsab', 'East Kolkata', 22.60295, 88.423987, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-259', 'Airport Enclave Residents Committee', 'North 24 Parganas', 22.505445, 88.294009, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-260', 'Ambagan Durga Puja Committee', 'North 24 Parganas', 22.471753, 88.351117, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-261', 'Atghara Noapara Baroary Durga Puja', 'North 24 Parganas', 22.6074, 88.4065, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-262', 'Banerjeepara Sarbojanin', 'North 24 Parganas', 22.631, 88.377, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-263', 'Biswanath Abasan Sharodotsav', 'North 24 Parganas', 22.5991, 88.4, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-264', 'Chitrakut Dham Durga Puja', 'North 24 Parganas', 22.6445, 88.4052, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-265', 'Debendra Nagar Sarbojanin', 'North 24 Parganas', 22.608, 88.379, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-266', 'Lake Town Adhibasi Brinda Durga Puja', 'North 24 Parganas', 22.605728, 88.402961, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-267', 'Lake Town Sarbojanin Durgotsav', 'North 24 Parganas', 22.604622, 88.403974, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-268', 'Maniratnam Flat Owner Association', 'North 24 Parganas', 22.6157, 88.4126, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-269', 'Patipukur Sarkari Abas Sharad Utsav Committee', 'North 24 Parganas', 22.606551, 88.395245, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-270', 'Regent Enclave Durga Puja', 'North 24 Parganas', 22.486573, 88.352579, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-271', 'Riya Gitanjali Housing Durga Puja', 'North 24 Parganas', 22.6339, 88.4005, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-272', 'Sabuj Sangha Durga Puja', 'North 24 Parganas', 22.532487, 88.255276, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-273', 'Sampoorna Tritiya Puja Committee', 'North 24 Parganas', 22.6321, 88.4015, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-274', 'Shastri Bagan Sporting Club Durgotsav Committee', 'North 24 Parganas', 22.6193, 88.4224, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-275', 'Siddha Happyville Cultural Committee', 'North 24 Parganas', 22.6308, 88.4077, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-276', 'Siddha Town Cultural Committee', 'North 24 Parganas', 22.630911, 88.471547, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-277', 'Sitalatala Mahila Samity', 'North 24 Parganas', 22.6331, 88.3905, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-278', 'SOE Residents Durga Puja', 'North 24 Parganas', 22.6236, 88.3956, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-279', '23 Pally Sarbojanin Durgotsab', 'South 24 Parganas', 22.4028, 88.3465, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-280', 'Bansdroni Shanti Sangha', 'South 24 Parganas', 22.473586, 88.360673, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-281', 'Brahmapur Boral Sarbojanin Durgotsab', 'South 24 Parganas', 22.4236, 88.3457, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-282', 'Brahmapur Sarbojanin Durgotsab', 'South 24 Parganas', 22.460239, 88.364448, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-283', 'Harindanga Milan Sangha Sarbojanin', 'South 24 Parganas', 22.4599, 88.3669, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-284', 'Jhikurberia Sarbojanin Durga Puja', 'South 24 Parganas', 22.4534, 88.388, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-285', 'Khamarkur Durga Puja', 'South 24 Parganas', 22.4557, 88.4207, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-286', 'Mukundapur Sarbojanin Durgotsav Committee', 'South 24 Parganas', 22.495626, 88.398449, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-287', 'Pockpari Sanghasree Sarbojanin Durgotsab Puja Committee', 'South 24 Parganas', 22.4068, 88.4064, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-288', 'Sonarpur Power House Sarbojanin Durgotsab', 'South 24 Parganas', 22.440875, 88.424637, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('extra-289', 'Subodh Garden Cultural & Welfare Society', 'South 24 Parganas', 22.3963, 88.4139, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-290', 'Sujaday Club Durga Puja', 'South 24 Parganas', 22.449, 88.4231, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-291', 'Thakurpukur Sister Nivedita Multipurpose Society', 'South 24 Parganas', 22.456, 88.3585, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-292', 'Udairampur Recreation Club', 'South 24 Parganas', 22.438, 88.3597, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-293', 'Uttar Purba Baishnabghata Patuli Sarbojanin Durgotsab Committee', 'South 24 Parganas', 22.4359, 88.374, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('extra-294', 'Windsor Greens Flat Owners Association', 'South 24 Parganas', 22.435, 88.364, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-295', 'Arabinda Nagar Arabinda Sangha Sarbojanin Durga Utsav', 'Howrah', 22.566887, 88.269715, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-296', 'Arupara Sarbojanin Durgotsab Committee', 'Howrah', 22.5901, 88.3284, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-297', 'Azad Hind Sangha Durga Puja', 'Howrah', 22.5644, 88.3179, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-298', 'Bachhri Durga Puja', 'Howrah', 22.6122, 88.3454, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-299', 'Bagnan Nabaneer Club Durga Puja', 'Howrah', 22.576, 88.3037, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-300', 'Balitikuri Netaji Balak Sangha', 'Howrah', 22.5707, 88.3194, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-301', 'Bantra Mohila Sangha Durga Puja', 'Howrah', 22.592787, 88.317996, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-302', 'Bantra Nabin Sangha Durga Puja', 'Howrah', 22.591681, 88.319009, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-303', 'Batore 41er Pally Sarbojanin', 'Howrah', 22.5646, 88.3452, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-304', 'Belepole Adams Club', 'Howrah', 22.5979, 88.3471, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-305', 'Brindabon Netaji Balak Sangha Durga Puja', 'Howrah', 22.5779, 88.3464, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-306', 'Daspara Panch Bhai Sangha', 'Howrah', 22.623221, 88.300084, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-307', 'Dharmatala Durga Puja', 'Howrah', 22.570078, 88.321519, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-308', 'Ghoshpara Sankalpa Sangha Durga Puja', 'Howrah', 22.5609, 88.3254, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-309', 'Ghoshpara Young Stars Durga Puja', 'Howrah', 22.6031, 88.3354, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-310', 'Guha Road Sarbojanin Mahapuja', 'Howrah', 22.61991, 88.350836, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-311', 'Howrah Jatiya Sevadal Club Durga Puja', 'Howrah', 22.5664, 88.3369, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-312', 'Ichapur Bayam Samity Durga Puja', 'Howrah', 22.592786, 88.305892, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-313', 'Ichapur Mitali Sangha Durga Puja', 'Howrah', 22.59168, 88.306905, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-314', 'Ichapur Sanghamitra Durga Puja', 'Howrah', 22.6123, 88.3024, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-315', 'Jhorehat Pachal Para Puja Committee', 'Howrah', 22.595, 88.3287, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-316', 'Kamardanga Sisu Sangha Durga Puja', 'Howrah', 22.6135, 88.3412, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-317', 'Kamardanga Sitalatala Barowari Durga Puja', 'Howrah', 22.5768, 88.3221, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-318', 'Kashipur Yubo Gosthi', 'Howrah', 22.607372, 88.308125, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-319', 'Kazi Bagan Lane Durga Puja', 'Howrah', 22.5563, 88.3051, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-320', 'Kishor Sangsad Club Durga Puja', 'Howrah', 22.5583, 88.3117, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-321', 'Madhusudan Das Lane & Bye Lane Sarbojanin Durgotsab', 'Howrah', 22.5686, 88.3249, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-322', 'Makardah Karuri Para Sarbojanin Durgotsav', 'Howrah', 22.5928, 88.3084, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-323', 'Milan Sangha Durga Puja', 'Howrah', 22.5731, 88.3382, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-324', 'Nabanagar Badamtala Sarbojanin Durgotsab', 'Howrah', 22.6114, 88.304, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-325', 'Salap Utsahi Sangha Durga Puja', 'Howrah', 22.5565, 88.3416, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-326', 'Salkia Baroari Durgatsob', 'Howrah', 22.598926, 88.34757, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-327', 'Salkia Chatra Bayam Samity Sarbojanin', 'Howrah', 22.59782, 88.348583, 'low', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-328', 'Salkia Sadharan Durga Puja', 'Howrah', 22.599112, 88.345456, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-329', 'Salkia Sitalatala Sarbojanin Durgotsab', 'Howrah', 22.6129, 88.3274, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-330', 'Shaktimoyee Sarbojanin Durgotsab Committee', 'Howrah', 22.5727, 88.3187, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-331', 'Shibpur Sastitala Durga Puja', 'Howrah', 22.5839, 88.3332, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-332', 'Subhaspally Shaktinagar Sarbojanin Durgatsav', 'Howrah', 22.5584, 88.3114, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-333', 'Torpedo Welfare Society Durga Puja', 'Howrah', 22.5932, 88.3132, 'low', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-334', 'Uttar Bantra Kumar Para Baroary Samity Durga Puja', 'Howrah', 22.592, 88.317, 'medium', null, false, null, null, null, null, null, null, '{}', null, '{}'),
('howrah-335', 'Uttar Salkia Sarbojanin Durgotsab', 'Howrah', 22.600507, 88.349632, 'medium', null, true, null, null, null, null, null, null, '{}', null, '{}')
on conflict (id) do nothing;
